### ISSUE TITLE
Check if a Binary Tree is BST

### ISSUE THREAD

**Issue by Ashutoshnegi880** [ravi-singh-100/HacktoberFest_DSA#5]
I would like to add code for checking if a given binary tree is BST or not. And explaining my approach with comments.

**Comment by 035pratheeksha** [comment]
I would love to solve this issue...Please assign this to me.

**Comment by ravi-singh-100** [comment]
> Please assign this issue to me.

This repo has some issue so please make a request on my other repo https://github.com/ravi-singh-100/DSA-Hacktober2022 .

**Comment by ravi-singh-100** [comment]
> I would love to solve this issue...Please assign this to me.

This repo has some issue so please make a request on my other repo https://github.com/ravi-singh-100/DSA-Hacktober2022 .

**Comment by ghost** [comment]
Would you, Please assign this issue to me ,,,,,

**Comment by 035pratheeksha** [comment]
> > I would love to solve this issue...Please assign this to me.
> 
> This repo has some issue so please make a request on my other repo https://github.com/ravi-singh-100/DSA-Hacktober2022 .

Is this not related to hacktoberfest?Because even if i have contributed i didnt get any progress
